image: Visual Studio 2022
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - nuget restore
  - dotnet restore

build:
  verbosity: minimal
  project: Cogito.Autofac.sln

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.Autofac

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/alethic/index.json
  username: wasabii
  api_key:
    secure: AEgTor17HOIs8YXyEDMsX2VmY+wyNmHhyu/fbc2zYEdIfl1ljq/2/+rsa9czOx9Z
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/

