<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net6.0;net472</TargetFrameworks>
        <Description>Provides various autofac utilities, and a new unique attribute registration system.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.3.2" />
        <PackageReference Include="Autofac.Extras.AggregateService" Version="7.0.1" />
        <PackageReference Include="Castle.Core" Version="5.2.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    </ItemGroup>

</Project>