<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net6.0;net472</TargetFrameworks>
        <Description>Provides various autofac utilities, and a new unique attribute registration system.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.2.0" />
        <PackageReference Include="Autofac.Extras.AggregateService" Version="6.1.2" />
        <PackageReference Include="Castle.Core" Version="5.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    </ItemGroup>

</Project>